### ISSUE TITLE
IncompatibleClassChangeError with CoordinatesDisplay 11.1.1 and BoxLib 14.2.0

### ISSUE THREAD

**Issue by andrescol24** [Boxadactle/coordinates-display#49]
## Clear and Consise description of the issue
Hi, I recently installed CoordinatesDisplay but I am geeting an error using the latest BoxLib version 14.2.0. **(I fixed it downloading the BoxLib 14.1.3)**

**What did you expect to happen?**
The game starts correctly.

**Steps to reproduce the issue:**
- Using Fabric: I downloaded latest version of CoordinatesDisplay and BoxLib, after starting the Minecraft game, it did not start showing that error: "Could not execute entrypoint stage 'client' due to errors, provided by 'coordinatesdisplay'!"

## Mod Information
**Minecraft version: 1.21**
**Mod version: 11.1.1**
**Other relevant mods: BoxLib 14.2.0 **

**Relevant logs (if applicable):**
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'coordinatesdisplay'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IncompatibleClassChangeError: class dev.boxadactle.coordinatesdisplay.command.ConfigSubcommand can not implement dev.boxadactle.boxlib.command.api.BClientSubcommand, because it is not an interface (dev.boxadactle.boxlib.command.api.BClientSubcommand is in unnamed module of loader net.
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at dev.boxadactle.coordinatesdisplay.CoordinatesDisplay.init(CoordinatesDisplay.java:55)
	at dev.boxadactle.coordinatesdisplay.fabric.CoordinatesDisplayFabric.onInitializeClient(CoordinatesDisplayFabric.java:27)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
```

**Comment by andrescol24** [comment]
Oh Sorry, this looks like as a duplication of #48
